learning_log/urls.py
from django.contrib import admin
from django.urls import path,include

#变量urlpatterns包含项目中应用程序的URL
#模块admin.site.urls定义 了可在管理网站中请求的所有URL
urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',include('users.urls')), #与任何以单词users打头的url都匹配
    path('',include('learning_logs.urls'))
]

learning_logs/urls.py
"定义learning_logs的URL模式"
#上面的说明旨在说明当前是哪个urls.py文件
from django.urls import path #path能够将URL映射到视图
from . import views #句点让python从使用的urls.py模块所在文件夹导入view.py

app_name = 'learning_logs' #app_name让Django区分项目内同名的urls.py文件
urlpatterns = [
    #主页
    path('',views.index,name = 'index'),
    #显示所有主题
    path('topics/', views.topics ,name = 'topics'),
    #特定主题的详细页面
    path('topics/<int:topic_id>/',views.topic,name='topic'),#第一个''中的topics让Django查找在基础URL后跟着topics的URL，
    #<int:topic_id>与包含在两个斜杠内的整数匹配，再将整数匹配到topic_id的实参中
    #若URL与该模式匹配，Django调用views中的topic()，并将储存在topic_id中的实参传递给topic()。在该函数中，将使用topic_id的值获取相应主题。
    path('new_topic/', views.new_topic, name='new_topic'),
    #用于添加新条目的页面
    path('new_entry/<int:topic_id>/',views.new_entry,name='new_entry'),#同样地<int:topic_id>捕获数值并给变量topic_id
    #用于编辑条目的页面
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry')
]
#urlpatterns是列表，包含可在应用程序learning_logs中请求的页面
#实际的URL模式为对函数path()的调用，函数接受三个实参 。
#第一个实参为一个字符串，帮助Django正确地路由（route）请求。
#收到请求的 URL后，Django力图 将请求 路由给一个视图。会 搜索所有 的 URL模式，找到与当前请求匹配的那个。
#Django忽视项目基础URL（http://localhost:8000）,因此空字符串''与 基础URL匹配。如果请求的 URL与任何既有RUL模式都不匹配，返回一个错误
#第二个实参为请求的URL与前述正则表达式匹配时调用oview.py中函数index（）
#第三个实参将这个URL模式的名称指定 为index，让我们在代码 的 其他地方能引用他。需要提供主页链接时，都将使用这个名称而不编写URL。

users/urls.py
"""为应用程序users定义url模式"""
from django.urls import path,include
from . import views

app_name='users' #命名给django区分其他应用程序。另外，即使是django提供的默认url，将其包含在应用程序users的文件后也可通过命名空间users访问。
urlpatterns=[
    #包含默认的身份验证url、
    path('',include('django.contrib.auth.urls')),
    #上面一句这里的URL模式与URL http://localhost:8000/users/login匹配，url中的单词users让django在users/ursls.py中查找，
    #单词login让他发送请求给django的默认视图login。
    #注册页面
    path('register/',views.register,name='register'),
    #上面一句话使得科研通过视图函数定义注册页面

]

learning_logs/models.py
from django.db import models
#模型告诉Django如何处理应用程序中存储的数据，模型就是一个类，包含属性跟方法。
from django.contrib.auth.models import User
# Create your models here.

#下面表示    用户将存储的主题    的模型：
class Topic(models.Model): #类继承于Model。
    "用户学习的主题"
    text = models.CharField(max_length = 200) #添加属性text,是CharField数据，即为文本。定义属性时要定义预留的空间
    date_added = models.DateTimeField(auto_now_add = True) #添加属性date_added，为一个DateTimeField数据，记录日期和时间的数据。
    #传递的实参auto_now_add在用户创建新主题时自动设置为当前日期和时间
    owner=models.ForeignKey(User,on_delete=models.CASCADE)#添加关联到用户的外键，用户被删除时主题也删除
    def __str__(self): #要告诉Django默认使用哪个属性显示有关主题的信息。调用方法__str__()来显示模型的简单表示
        "返回模型的字符串表示"
        return self.text

class Entry(models.Model): #类继承于基类Model
    "学到的有关某个主题的具体知识"
    #属性topic是个ForeignKey实例；属性text是个TextField实例
    # foreignkey是数据库术语，指向数据库另外一条记录，这里将每个条目关联到特定主题
    #创建每个主题Topic时，都分配了一个键（ID）。需要在两项数据之间建立联系时，Django使用与每项信息相关联的键。
    topic = models.ForeignKey(Topic, on_delete = models.CASCADE)  #实参on_delete = models.CASCADE让Django删除主题时同时删除所有关联条目，级联删除。
    text = models.TextField() #TextField长度不受限制
    date_added = models.DateTimeField(auto_now_add = True) #date_added让我们能够按创建顺序呈现条目并在条目旁放时间戳

    class  Meta: #在Entry类中嵌套Meta类，定义元数据，用于管理模型的额外信息
        #它能让我们设置特殊属性，让Django在需要时使用Entries来表示多个条目（这里指的是网页上admin界面显示多个条目时的情况）
        #没有这个类，Django将使用Entrys表示多个条目
        verbose_name_plural = 'entries' #verbose_name_plural指定复数形式是什么

    def __str__(self):  #__str__()告诉Django呈现条目时显示哪些信息
        "返回模型的字符串表示"
        return f"{self.text[:50]}..."
        #这种为f字符串，f是format设置格式的简写。在引号前加f，可将字符串中插入变量值，只要讲变量用花括号括起来
        #这里只显示前50个字符并加字符“。。。”字面表示还有剩下的

learning_logs/forms.py
from django import forms

from .models import Topic,Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text':''}

class EntryForm(forms.ModelForm):
    class Meta:
        model=Entry#表单基于的模型
        fields = ['text']#表单包含的字段
        labels = {'text':''}
        widgets = {'text':forms.Textarea(attrs={'cols':80})}
        #widget小部件，是一个html表单元素，如单行文本框，多行文本区域或下拉列表
        #使用forms.Textarea，定制了text的宽度为80列，默认为40.

learning_logs/views.py
from django.shortcuts import render, redirect
#函数render（）根据视图 提供的数据渲染响应,redirect为重定向用，将视图名作为参数并重定向到该视图
from django.contrib.auth.decorators import login_required
from django.http import Http404
from .models import Topic,Entry #导入与数据相关的模型
from .forms import TopicForm, EntryForm

# Create your views here.在这里创建视图，view.py是在运行命令python manage.py startapp时自动生成的
#视图函数接受请求中的信息，使用定义页面外观的模板，准备好生成页面所需数据，再将 这些数据 发送给服务器
#当learning_logs的程序运行时，匹配了模式，Django将在views.py中查找函数index()，再将对象request传递给视图函数
def index(request):
    "学习笔记的主页"
    return render(request,'learning_logs/index.html')  #这里有两个实参，一个是对象request，另外一个是 可用于创建页面的模板

@login_required
#未登录时通过settings中的LOGIN_URL中的变量重定向
def topics(request): #形参为Django从服务器收到的request对象
    "显示所有主题"
    #topics = Topic.objects.order_by('date_added')
    # 查询数据库，请求提供Topic对象，并根据属性date_added排序,返回的查询集储存在topics中
    topics = Topic.objects.filter(ower=request.user).order_by('date_added')
    # 用户登录后，request对象将有一个user属性，储存有关该用户的信息，查询Topic.objects.filter(ower=request.user)让Django只从
    #数据库中获取owner属性为当前用户的Topic对象。
    context = {'topics' : topics}
    #context为定义将发送给模板的上下文（上下文是个字典）。键--将在模板中用来访问数据的名称，值--发送给模板的数据。注意这里只有一个键值对。
    return render(request,'learning_logs/topics.html',context) #除了对象request跟模板路径外，还将变量context传递给render（）。

@login_required
def topic(request, topic_id): #除了request对象外，还包含在urls.py由/<int:topic_id>/捕获的形参topic_id。
    "显示单个主题及所有条目"
    topic = Topic.objects.get(id=topic_id) #使用get()获取指定的主题号，这行跟下一行entries都为查询代码，向数据库查询。不过可在Django shell先尝试，快速反馈。
    #确认请求的主题属于当前用户,渲染前检查
    if topic.owner != request.user:
        raise Http404

    entries = topic.entry_set.order_by('-date_added') #获取与主题关联的条目，因为有"-"，根据date_added进行降序排序
    context = {'topic': topic,'entries':entries} #主题跟条目都储存到了字典context
    return render(request,'learning_logs/topic.html',context) #把字典传给了模板topic.html

@login_required
def new_topic(request):
    #用户初次请求该页面时，浏览器会发送get请求，用户填写提交表单时浏览器发送POST请求。
    """添加新主题"""
    if request.method != 'POST': #确定请求方法是get还是post
        #未提交数据：创建一个新表单
        form = TopicForm()#实例化topicform没指定任何参数，django将创建空表单给用户写
    else:
        #post提交的数据，对数据进行处理
        form=TopicForm(data=request.POST)
        if form.is_valid(): #提交的信息是否有效需要验证，如填写所有必不可少字段与字段长度大小是否超限
            new_topic = form.save(commit=False)#实参的作用是-先修改新主题再保存
            new_topic.owner = request.user#读取request里的user再设置为当前主题的owner
            new_topic.save()#完事后再调用默认save
            #form.save()
            return redirect('learning_logs:topics')

    #显示空表单或指出表单数据无效
    context={'form':form}
    return render(request,'learning_logs/new_topic.html',context)

@login_required
def new_entry(request,topic_id):
    #用户初次请求该页面时，浏览器会发送get请求，用户填写提交表单时浏览器发送POST请求。
    """在特定主题添加新条目"""
    topic=Topic.objects.get(id=topic_id)#需要知道针对哪个主题所作操作

    if request.method != 'POST': #确定请求方法是get还是post
        #未提交数据：创建一个新表单
        form = EntryForm()#实例化Entryform没指定任何参数，django将创建空表单给用户写
    else:
        #post提交的数据，对数据进行处理
        form=EntryForm(data=request.POST)
        if form.is_valid(): #提交的信息是否有效需要验证，如填写所有必不可少字段与字段长度大小是否超限
            new_entry=form.save(commit=False)#commit=false让django创建新条目对象赋给new_entry但不保存到数据库
            new_entry.topic=topic#将属性topic设置为函数开头获取的主题
            new_entry.save() #这里才保存到数据库并与正确主题关联
            return redirect('learning_logs:topic',topic_id=topic_id)#重定向到视图函数topic还需要实参topic_id

    #显示空表单或指出表单数据无效
    context={'topic':topic, 'form':form} #这是上下文字典
    return render(request,'learning_logs/new_entry.html',context)

@login_required
def edit_entry(request, entry_id):
    """编辑既有条目"""
    #第一步先获取条目与关联的主题
    entry=Entry.objects.get(id=entry_id)
    topic=entry.topic
    #获取指定的条目，检查条目关联的主题所有者是否是当前登录用户
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        #初次请求：使用当前条目填充表单
        #使用实参instance=entry创建EntryForm实例，创建表单实例并用条目对象的信息填充它
        #用户能看到数据并能编辑
        form=EntryForm(instance=entry)
    else:
        #POST提交的数据：对数据进行处理
        form=EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save() #这里不指定任何实参因为已经关联到特定条目了
            return redirect('learning_logs:topic',topic_id=topic.id)

    context={'entry':entry,'topic':topic,'form':form}
    return render(request,'learning_logs/edit_entry.html',context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %} <!--加载django-bootsrap4中的模板标签集-->
<!DOCTYPE html> <!--声明为html文档-->
<html lang="en"> <!--声明使用英语-->
<head> <!--头部不包含任何内容，只是向浏览器提供正确显示页面所需信息-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Learning Log</title> <!--在浏览器打开网页学习笔记时，标题栏显示title元素的内容-->

    {%bootstrap_css%} <!--django-bootstrap4的一个自定义模板标签，让bootstrap包含所有样式文件-->
    {%bootstrap_javascript jquery='full'%} <!--启用所有标签行为如折叠导航栏-->
</head>

<!--适配手机窄屏幕与电脑宽屏幕，分三部分定义导航栏-->
<body><!--主体开始，页面上的内容展示-->
  <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
      <!--nav元素，导航链接部分.
      对元素内的部分，都将根据此处navbar和navbar-expand-md等选择器定义的bootstrap样式规则来设置样式。
      选择器决定了样式规则将应用于页面上的哪些元素。
      navbar-light bg-light选择使用浅色主题设置导航栏颜色。
      md表示下边距，4的数值确保导航栏页面其他部分之间有一些空白区域。
      border在浅色背景周围添加很细的边框，将导航栏与页面其他部分分开。-->

      <a class="navbar-brand" href="{% url 'learning_logs:index'%}">
          Learning Log
      </a>
      <!--指定在导航栏最左端显示项目名并设置为到主页的链接，将出现在这个项目的每个页面中。
      选择器navbar-brand设置这个链接的样式，使得其比其他链接更显眼。-->

      <button class="navbar-toggler" type="button" data-toggle="collapse"
              data-target="#navbarCollapse" aria-controls="navbarCollapse"
              aria-expanded="false" aria-lable="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>
      <!--定义了一个按钮，将在浏览窗口太窄，无法水平显示整个导航栏时显示出来。单机按钮回出现下拉列表，包含所有导航元素
      用户缩小浏览窗口或在屏幕较小的移动设备上显示网站时，collapse会导致导航栏折叠起来。-->

      <!--开启导航栏的新区域。div是division分隔的缩写。
      在div起始标签中定义的样式和行为规范将影响下一个结束标签/div之间的所有元素。
      这里定义了屏幕或窗口太窄时将折叠起来的导航栏部分的起始位置。-->
      <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto"><!--定义了一组链接。-->
              <li class="nav-item"><!--这里只有一个列表项-到显示所有主题的页面链接。-->
                  <a class="nav-link" href="{% url 'learning_logs:topics'% }">Topics</a>
              </li>
          </ul>

          <ul class="navbar-nav ml-auto"><!--用起始标签ul定义了另一组链接。选择器ml-auto表示自动左边距。确保在右侧-->
              {% if user.is_authenticated %}<!--判断是否登录-->
                <li class="nav-item">
                    <span class="navbar-text">Hello,{{user.username}}.</span>
                    <!--span元素用于设置区域内一系列文本或元素样式。-->
                </li>
                <li class="nav-item">
                    <a class="navbar-link" href="{% url 'users:logout'%}">Log out</a>
                </li>
              {% else %}
                <li class="nav-item">
                    <a class="navbar-link" href="{% url 'users:register'%}">Register </a>
                </li>
                <li class="nav-item">
                    <a class="navbar-link" href="{% url 'users:login'%}"> Log in</a>
                </li>
              {% endif %}
          </ul>
      </div><!--div元素（屏幕太窄时折叠起来的导航栏部分）结束-->
  </nav><!--导航链接部分结束-->
  <!--要在导航栏添加其他链接，可在既有ul元素添加li元素并设置样式。-->

  <!--定义两个块，供各个页面放置其特有内容。-->
  <main role="main" class="container"><!--main起始标签，main元素用于定义页面主体的最重要部分。
  这里定义了bootstrap选择器container，一种对页面元素进行编组的简单方式。在容器中放置两个div元素。-->
      <div class="pb-2 mb-2 border-bottom">
          <!--第一个元素包含一个page_header块，在大多数页面使用它指定标题。
          pb-2指将下内边距设置为合适的值。标题下面添加边框，所以使用选择器border-bottom，在page_header块的下面添加细框-->
          {% block page_header %}{% endblock page_header %}
      </div>
      <div>
          <!--第二个元素未指定样式，在具体页面中，可根据需要设置内容样式。-->
          {% block content %}{% endblock content %}
      </div>
  </main>

</body>

</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends 'learning_logs/base.html' %} <!--继承于base.html-->

{% block content %}
    <p><a href="{%url 'learning_logs:topic' topic.id%}">{{topic}}</a></p><!--知道在哪个主题并可以链接过去-->

    <p>Edit entry:</p>

    <form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post"> <!--定义表单并告诉服务器要发送到哪，
    这里发送给视图函数edit_entry(),以post请求的方式体提交,entry.id传给视图函数实参entry_id-->
        {% csrf_token %}<!--防止攻击者利用表单获得对服务器未经授权的访问-->
        {{ form.as_p }}<!--显示表单，as_p以段落格式渲染所有表单元素-->
        <button name="submit">Save changes</button> <!--创建提交按钮-->
    </form>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
<!--其中<p></p>标签用于标识段落。前者指出段落开头，后者指出结尾。-->
<!--标题-->
<!-- <p>Learning Log</p> 旧的这个标题被换了。新的extends用来说明继承父模板-->
{% extends  "learning_logs/base.html" %}
<!--上面这行 代码导入模板base.html的所有内容，让index.html能够指定要在content块预留的空间中添加的内容。-->
<!--下面是描述部分，其中{block c}用来标识块标签部分。不从父模板中继承的内容都包含在content块中。-->

<!---->
{% block page_header %}<!--告诉django接下来定义page_header块包含的内容。-->
  <div class="jumbotron"><!--jumbotron就是应用了一系列样式设置命令的div元素。
  这里使用选择器jumbotron应用这组来自bootstrap库的样式设置指令。-->
      <h1 class="dispaly-3">Track your learning.</h1><!--h1是一级标题。display-3让标题更窄更高-->

      <p class="lead">Make your own Learning Log, and keep a list of the topics you're learning about.
      Whenever you learn something new about a topic,make an entry sumarizing what you've learned.</p>

      <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
         role="button">Register &raquo;</a>
      <!--创建按钮（非文本链接）邀请用户注册。代码%raquo是一个HTML实体，表示“>>”符号-->

  </div>
{% endblock page_header %}<!--结束块，如无其他内容则不需要定义content块。-->

learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %} <!--继承于base.html-->

{% block content %}
    <p><a href="{%url 'learning_logs:topic' topic.id%}">{{topic}}</a></p><!--知道在哪个主题并可以链接过去-->

    <p>Add a new entry:</p>

    <form action="{% url 'learning_logs:new_entry' topic.id %}" method="post"> <!--定义表单并告诉服务器要发送到哪，
    这里发送给视图函数new_entry(),以post请求的方式体提交-->
        {% csrf_token %}<!--防止攻击者利用表单获得对服务器未经授权的访问-->
        {{ form.as_p }}<!--显示表单，as_p以段落格式渲染所有表单元素-->
        <button name="submit">Add entry</button> <!--创建提交按钮-->
    </form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends 'learning_logs/base.html' %} <!--继承于base.html-->

{% block content %}
    <p>Add a new topic:</p>

    <form action="{% url 'learning_logs:new_topic' %}" method="post"> <!--定义表单并告诉服务器要发送到哪，
    这里发送给视图函数new_topic(),以post请求的方式体提交-->
        {% csrf_token %}<!--防止攻击者利用表单获得对服务器未经授权的访问-->
        {{ form.as_p }}<!--显示表单，as_p以段落格式渲染所有表单元素-->
        <button name="submit">Add topic</button> <!--创建提交按钮-->
    </form>

{% endblock content %}

learning_logs/templates/learning_logs/old_base.html
<!--父模板，包含所有页面都有的元素，其他模板都继承于它-->
<!--第一部分创建包含项目名的段落，也是到主页的链接 。
1、创建连接时使用了模板标签，用{}表示，里面生成要在页面中显示的信息。
模板标签{ url 'learning_logs:index' }生成一个URL，与在learning_logs/urls.py中定义的名为index的URL模式匹配。
本例中，learning_logs是一个命名空间，index是该命名空间中一个名称独特的URL模式。
命名空间来自在文件learning_logs/urls.py中赋给app_name的值。
2、在简单的HTML页面中，链接是使用锚标签<a>定义的
3、模板标签是一小段代码，用花括号跟百分号表示，指向learning_logs/urls.py中匹配的格式
-->
<p>
    <a href="{% url 'learning_logs:index' %}">Learning Log</a> - <!--这里添加一个连字符"-"，再添加使用模板标签{url}指向所有主题的链接-->
    <a href="{% url 'learning_logs:topics' %}">Topics</a> - <!--这行让Django生成链接，与learning_logs/url.py中名为topics的URL模式匹配。-->
    {% if user.is_authenticated %} <!--Django身份验证系统中，每个模板都可用变量user，有属性is_authenticated.-->
      Hello,{{ user.username }}.
      <a href="{% url 'users:logout' %}">Log out</a>
    {% else %}
      <a href="{% url 'users:register' %}">Register</a>-
      <a href="{% url 'users:login' %}">Log in</a>
    {% endif %}
</p>
<!--通过模板标签生成URL，能确保链接是最新的：只需修改urls.py中的URL模式，Django就会在页面下次被请求时自动插入修改后的URL。-->

{% block content %}{% endblock content %}
<!--这里插入一对 块标签 。块名为 content ,是一个占位符，包含的信息由子模版指定。子模板并非必须定义父模板中的每个块。
所以可以在父模板多预留块来预留空间。>

learning_logs/templates/learning_logs/old_index.html
<!--其中<p></p>标签用于标识段落。前者指出段落开头，后者指出结尾。-->
<!--标题-->
<!-- <p>Learning Log</p> 旧的这个标题被换了。新的extends用来说明继承父模板-->
{% extends  "learning_logs/base.html" %}
<!--上面这行 代码导入模板base.html的所有内容，让index.html能够指定要在content块预留的空间中添加的内容。-->
<!--下面是描述部分，其中{block c}用来标识块标签部分。不从父模板中继承的内容都包含在content块中。-->
{% block content %}
<p>Learning Log helps you keep track of your  learning, for any topic you're learning about.</p>
{% endblock content %}<!--标签{ endblock c}指出内容定义结束的位置，{endb}不一定指定块名称，但是有多个的时候指定比较好-->

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %} <!--继承于base.html-->
<!--设置单个topic的页面包含更多内容。使用bootstrap的card组件完成每个条目。card是带灵活的预定义样式的div，适合显示主题条目。-->

{% block page_header %}<!--将主题放page_header块-->
  <h3>{{ topic }}</h3>
{% endblock page_header %}

{% block content %}

    <p>
        <a href="{% url 'learning_logs:new_entry' topic.id %}">Add a new entry</a>
    </p>

{% for entry in entries %} <!--遍历条目-->
  <div class="card mb-3"><!--不将每个条目作为一个列表项，创建一个带选择器card的div元素。-->
      <h4 class="card-header"><!--div元素里的嵌套元素，是哥标题，带选择器card-header的h4元素。-->
          {{ entry.date_added | date:'M d, Y H:i' }} <!--列出时间戳，显示属性date_added的值，“|”表示模板过滤器，对模板的值进行修改。-->
          <!--date:'M d, Y H:i'的过滤器显示如月，天，年，时间-->
          <small><!--编辑条目放置small条目，看起来比时间元素小一点。-->
              <a href="{%url 'learning_logs:edit_enty' entry.id %}">Edit entry</a> <!--放在每个条目后面 -->
          </small>
      </h4>

      <div class="card-body"><!--第二个嵌套条目，带选择器card-body的div元素。将条目内容放框内。-->
            {{ entry.text | linebreaks }}<!--显示text的完整值，不仅仅50字。linebreaks过滤器将包含换行符的长条目转换为浏览器能理解的格式，以免不间断显示。-->
      </div>
  </div>
  {% empty %} <!--当无内容时打印下面的信息。-->
        <p>There are no entries for this topic yet.</p>
{% endfor %}

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %} <!--使用extends 来继承base.html，再定义content块。-->

<!--这个文件没有用bootstrap4的自定义标签，所以不用写标签load bootstrap4-->

{% block page_header %}
  <h1>Topics</h1>
{% endblock page_header %}

{% block content %}

    <ul> <!--页面主题是个项目列表，html中成为无序列表，用标签<ul>表示。-->
        {% for topic in topics %} <!--相当于for循环的模板标签,遍历调用topics.html文件的字典context中的列表topics-->
            <li><h3>
                <a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a>
                <!--使用模板标签url根据learning_logs中名为topic的URL模式生成了合适的链接。
                URL模式需要提供实参topic_id，所以在模板属性添加了topic.id。其中topic.id检查主题并获取其id值，而topic_id是指向该id的引用。
                现在主页列表都是链接了对应到相应主题。
                -->
            </h3></li> <!--HTML标签<li>中的内容表示项目列表项。 要将变量打印，要用双花括号 把变量名括起来。双花括号里面的是模板变量。-->
        {% empty %} <!--标签模板{ empty }告诉Django列表topics为空时怎么办。-->
        <li><h3>No topics have been added yet.</h3></li>
        {% endfor %} <!--模板中，要用{ endfor }显式地指出for循环的结束。结束for循环用-->
    </ul> <!--结束项目列表用-->

    <h3><a href="{% url 'learning_logs:new_topic' %}">Add a new topic</a></h3>

{% endblock content %}